"""empty message

Revision ID: 36820e0dae12
Revises: f5368642edd2
Create Date: 2023-02-19 08:26:54.356794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36820e0dae12'
down_revision = 'f5368642edd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_admin = True")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
