"""empty message

Revision ID: ac393ec3ca26
Revises: 36820e0dae12
Create Date: 2023-02-19 08:33:40.818706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac393ec3ca26'
down_revision = '36820e0dae12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.execute('UPDATE users SET is_admin=False WHERE id>1')
    op.execute('UPDATE users SET is_admin=True WHERE id=1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
